defmodule Athena.KTailsTest do
  use ExUnit.Case
	alias Athena.KTails, as: KTails
	alias Athena.EFSMTest, as: EFSMTest

  test "Get tails" do
    assert KTails.get_tails(EFSMTest.efsm1, 1) == 
										%{"0" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "coke"}}], label: "select", outputs: [],
															 sources: [%{event: 1, trace: 1}, %{event: 1, trace: 2}], updates: []}],
														[%{guards: [{:eq, {:v, :i1}, {:lit, "pepsi"}}], label: "select", outputs: [], sources: [%{event: 1, trace: 3}],
															 updates: []}]],
											"1" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "50"}}],
															 sources: [%{event: 2, trace: 1}], updates: []}],
														[%{guards: [{:eq, {:v, :i1}, {:lit, "100"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 2, trace: 2}], updates: []}]],
											"2" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 1}], updates: []}]],
											"3" => [[%{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 4, trace: 1}],
															 updates: []}]], 
											"4" => [],
											"5" => [[%{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 3, trace: 2}],
															 updates: []}]], 
											"6" => [],
											"7" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "50"}}],
															 sources: [%{event: 2, trace: 3}], updates: []}]],
											"8" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 3}], updates: []}]],
											"9" => [[%{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "pepsi"}}], sources: [%{event: 4, trace: 3}],
															 updates: []}]], 
											"10" => []}
    assert KTails.get_tails(EFSMTest.efsm1, 2) == 
										%{"0" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "coke"}}], label: "select", outputs: [],
															 sources: [%{event: 1, trace: 1}, %{event: 1, trace: 2}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "50"}}],
															 sources: [%{event: 2, trace: 1}], updates: []}],
														[%{guards: [{:eq, {:v, :i1}, {:lit, "coke"}}], label: "select", outputs: [],
															 sources: [%{event: 1, trace: 1}, %{event: 1, trace: 2}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "100"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 2, trace: 2}], updates: []}],
														[%{guards: [{:eq, {:v, :i1}, {:lit, "pepsi"}}], label: "select", outputs: [], sources: [%{event: 1, trace: 3}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "50"}}],
															 sources: [%{event: 2, trace: 3}], updates: []}]],
											"1" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "50"}}],
															 sources: [%{event: 2, trace: 1}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 1}], updates: []}],
														[%{guards: [{:eq, {:v, :i1}, {:lit, "100"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 2, trace: 2}], updates: []},
														 %{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 3, trace: 2}], updates: []}]],
											"2" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 1}], updates: []},
														 %{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 4, trace: 1}], updates: []}]],
											"3" => [[%{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 4, trace: 1}],
															 updates: []}]], 
											"4" => [],
											"5" => [[%{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 3, trace: 2}],
															 updates: []}]], 
											"6" => [],
											"7" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "50"}}],
															 sources: [%{event: 2, trace: 3}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 3}], updates: []}]],
											"8" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 3}], updates: []},
														 %{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "pepsi"}}], sources: [%{event: 4, trace: 3}], updates: []}]],
											"9" => [[%{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "pepsi"}}], sources: [%{event: 4, trace: 3}],
															 updates: []}]], 
											"10" => []}
    assert KTails.get_tails(EFSMTest.efsm1, 3) == 
										%{"0" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "coke"}}], label: "select", outputs: [],
															 sources: [%{event: 1, trace: 1}, %{event: 1, trace: 2}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "50"}}],
															 sources: [%{event: 2, trace: 1}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 1}], updates: []}],
														[%{guards: [{:eq, {:v, :i1}, {:lit, "coke"}}], label: "select", outputs: [],
															 sources: [%{event: 1, trace: 1}, %{event: 1, trace: 2}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "100"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 2, trace: 2}], updates: []},
														 %{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 3, trace: 2}], updates: []}],
														[%{guards: [{:eq, {:v, :i1}, {:lit, "pepsi"}}], label: "select", outputs: [], sources: [%{event: 1, trace: 3}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "50"}}],
															 sources: [%{event: 2, trace: 3}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 3}], updates: []}]],
											"1" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "50"}}],
															 sources: [%{event: 2, trace: 1}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 1}], updates: []},
														 %{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 4, trace: 1}], updates: []}],
														[%{guards: [{:eq, {:v, :i1}, {:lit, "100"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 2, trace: 2}], updates: []},
														 %{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 3, trace: 2}], updates: []}]],
											"2" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 1}], updates: []},
														 %{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 4, trace: 1}], updates: []}]],
											"3" => [[%{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 4, trace: 1}],
															 updates: []}]], 
											"4" => [],
											"5" => [[%{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "coke"}}], sources: [%{event: 3, trace: 2}],
															 updates: []}]], 
											"6" => [],
											"7" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "50"}}],
															 sources: [%{event: 2, trace: 3}], updates: []},
														 %{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 3}], updates: []},
														 %{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "pepsi"}}], sources: [%{event: 4, trace: 3}], updates: []}]],
											"8" => [[%{guards: [{:eq, {:v, :i1}, {:lit, "50"}}], label: "coin", outputs: [{:assign, :o1, {:lit, "100"}}],
															 sources: [%{event: 3, trace: 3}], updates: []},
														 %{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "pepsi"}}], sources: [%{event: 4, trace: 3}], updates: []}]],
											"9" => [[%{guards: [], label: "vend", outputs: [{:assign, :o1, {:lit, "pepsi"}}], sources: [%{event: 4, trace: 3}],
															 updates: []}]], 
											"10" => []}
  end

	test "Compare" do
		assert KTails.compare_all(EFSMTest.efsm1, 1) == %{{"0","1"}=>0,{"0","10"}=>0,{"0","2"}=>0,{"0","3"}=>0,{"0","4"}=>0,{"0","5"}=>0,{"0","6"}=>0,{"0","7"}=>0,{"0","8"}=>0,{"0","9"}=>0,{"1","10"}=>0,{"1","2"}=>3.02,{"1","3"}=>0,{"1","4"}=>0,{"1","5"}=>0,{"1","6"}=>0,{"1","7"}=>3.02,{"1","8"}=>3.02,{"1","9"}=>0,{"10","2"}=>0,{"10","3"}=>0,{"10","4"}=>0,{"10","5"}=>0,{"10","6"}=>0,{"10","7"}=>0,{"10","8"}=>0,{"10","9"}=>0,{"2","3"}=>0,{"2","4"}=>0,{"2","5"}=>0,{"2","6"}=>0,{"2","7"}=>1.51,{"2","8"}=>2.0,{"2","9"}=>0,{"3","4"}=>0,{"3","5"}=>1.5,{"3","6"}=>0,{"3","7"}=>0,{"3","8"}=>0,{"3","9"}=>1.01,{"4","5"}=>0,{"4","6"}=>0,{"4","7"}=>0,{"4","8"}=>0,{"4","9"}=>0,{"5","6"}=>0,{"5","7"}=>0,{"5","8"}=>0,{"5","9"}=>1.01,{"6","7"}=>0,{"6","8"}=>0,{"6","9"}=>0,{"7","8"}=>1.51,{"7","9"}=>0,{"8","9"}=>0}
		assert KTails.compare_all(EFSMTest.efsm1, 2) == %{{"0","1"}=>4.53,{"0","10"}=>0,{"0","2"}=>0,{"0","3"}=>0,{"0","4"}=>0,{"0","5"}=>0,{"0","6"}=>0,{"0","7"}=>4.53,{"0","8"}=>0,{"0","9"}=>0,{"1","10"}=>0,{"1","2"}=>4.52,{"1","3"}=>0,{"1","4"}=>0,{"1","5"}=>0,{"1","6"}=>0,{"1","7"}=>5.02,{"1","8"}=>4.03,{"1","9"}=>0,{"10","2"}=>0,{"10","3"}=>0,{"10","4"}=>0,{"10","5"}=>0,{"10","6"}=>0,{"10","7"}=>0,{"10","8"}=>0,{"10","9"}=>0,{"2","3"}=>0,{"2","4"}=>0,{"2","5"}=>0,{"2","6"}=>0,{"2","7"}=>1.51,{"2","8"}=>3.01,{"2","9"}=>0,{"3","4"}=>0,{"3","5"}=>1.5,{"3","6"}=>0,{"3","7"}=>0,{"3","8"}=>0,{"3","9"}=>1.01,{"4","5"}=>0,{"4","6"}=>0,{"4","7"}=>0,{"4","8"}=>0,{"4","9"}=>0,{"5","6"}=>0,{"5","7"}=>0,{"5","8"}=>0,{"5","9"}=>1.01,{"6","7"}=>0,{"6","8"}=>0,{"6","9"}=>0,{"7","8"}=>1.51,{"7","9"}=>0,{"8","9"}=>0}
		assert KTails.compare_all(EFSMTest.efsm1, 4) == %{{"0","1"}=>6.029999999999999,{"0","10"}=>0,{"0","2"}=>0,{"0","3"}=>0,{"0","4"}=>0,{"0","5"}=>0,{"0","6"}=>0,{"0","7"}=>5.54,{"0","8"}=>0,{"0","9"}=>0,{"1","10"}=>0,{"1","2"}=>4.52,{"1","3"}=>0,{"1","4"}=>0,{"1","5"}=>0,{"1","6"}=>0,{"1","7"}=>6.029999999999999,{"1","8"}=>4.03,{"1","9"}=>0,{"10","2"}=>0,{"10","3"}=>0,{"10","4"}=>0,{"10","5"}=>0,{"10","6"}=>0,{"10","7"}=>0,{"10","8"}=>0,{"10","9"}=>0,{"2","3"}=>0,{"2","4"}=>0,{"2","5"}=>0,{"2","6"}=>0,{"2","7"}=>1.51,{"2","8"}=>3.01,{"2","9"}=>0,{"3","4"}=>0,{"3","5"}=>1.5,{"3","6"}=>0,{"3","7"}=>0,{"3","8"}=>0,{"3","9"}=>1.01,{"4","5"}=>0,{"4","6"}=>0,{"4","7"}=>0,{"4","8"}=>0,{"4","9"}=>0,{"5","6"}=>0,{"5","7"}=>0,{"5","8"}=>0,{"5","9"}=>1.01,{"6","7"}=>0,{"6","8"}=>0,{"6","9"}=>0,{"7","8"}=>1.51,{"7","9"}=>0,{"8","9"}=>0}
	end

end
