language: erlang
otp_release:
   - 18.3
   - 18.2
before_install:
   - git clone https://github.com/elixir-lang/elixir
   - make -C elixir
   - export PATH="$PATH:$PWD/elixir/bin"
   - mix local.hex --force
   - mix deps.get
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: mix test --max-cases 1
