language: erlang
otp_release:
   - 17.0
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -y dos2unix
   - wget http://www.dcs.shef.ac.uk/~ramsay/z3-4.1.1.tar.bz2
   - tar -jxf z3-4.1.1.tar.bz2
   - pushd `pwd`
   - cd z3
   - autoconf
   - ./configure
   - make
   - make a
   - popd
   - wget http://downloads.sourceforge.net/project/z3str/Z3-str_20140720.tar.bz2
   - tar -jxf Z3-str_20140720.tar.bz2
   - pushd `pwd`
   - cd Z3-str_20140720
   - sed -i 's|Z3_path = .*|Z3_path = '`pwd`'/../z3|' Makefile
   - make
   - popd
   - git clone https://github.com/elixir-lang/elixir
   - make -C elixir
   - chmod +x travis-path-fix.sh
   - ./travis-path-fix.sh
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: mix test
