language: erlang
otp_release:
# 17.2 not supported by travis
# 17.1 some deps fail to build (hackney?)
   - 17.3
   - 17.0
before_install:
   - git clone https://github.com/elixir-lang/elixir
   - make -C elixir
   - export PATH="$PATH:$PWD/elixir/bin"
   - mix local.hex --force
   - mix deps.get
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: mix test
